## This R script computes the inverse of a matrix or retrieves the inverse of a matrix
## from the global environment if this inverse has already been computed.


## makeCacheMatrix() returns a list containing functions used by cacheSolve() to 
##    initialize (set) and retrieve (get) data
##    define functions to compute (setsolve) or retrieve (getsolve) inverse

makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  set <- function(y) {
    x <<- y
    inverse <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) inverse <<- solve
  getsolve <- function() inverse
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}

## The cacheSolve() function will compute the inverse of a matrix or will retrieve this inverse
## from the cache memory of the global environment if it has already been computed previously.
## The cacheSolve() function needs an argument generated by makeCacheMatrix().
## makeCacheMatrix()needs a matrix argument.
## As a consequence, after having defined a matrix with:
## > MyMatrix<-matrix(c(1,2,3,4),nrow=2,ncol=2)
## > MyMatrix
##        [,1] [,2]
## [1,]    1    3
## [2,]    2    4
## we will call cacheSolve() with:
## > cacheMatrix<-makeCacheMatrix(MyMatrix)
## > cacheSolve(cacheMatrix)
##      [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5
## A second execution will display the message "getting cached data" 
## as we will retrieve the inverse already computed and stored in the environment.
## > cacheSolve(cacheMatrix)
## getting cached data
##      [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5
## NB: calling cacheSolve () with:
## cacheSolve(makeCacheMatrix(MyMatrix))
## will never use the cach and will always recompute the inverse 
## as we always initialize the object typed makeCacheMatrix().


cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  inverse <- x$getsolve()
  if(!is.null(inverse)) {
    message("getting cached data")
    return(inverse)
  }
  data <- x$get()
  inverse <- solve(data, ...)
  x$setsolve(inverse)
  inverse
}